//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account_Group()
        {
            this.Account_Group_Member = new HashSet<Account_Group_Member>();
            this.APX_Portfolio_Statement = new HashSet<APX_Portfolio_Statement>();
            this.Portfolio_Benchmark = new HashSet<Portfolio_Benchmark>();
            this.Portfolio_Investment_Objective = new HashSet<Portfolio_Investment_Objective>();
            this.Portfolio_Performance = new HashSet<Portfolio_Performance>();
            this.Portfolio_Returns = new HashSet<Portfolio_Returns>();
        }
    
        public int id { get; set; }
        public int source_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> perf_start_date { get; set; }
        public Nullable<System.DateTime> progress_start_date { get; set; }
        public int firm_user_group_id { get; set; }
    
        public virtual Firm_User_Group Firm_User_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Group_Member> Account_Group_Member { get; set; }
        public virtual Source Source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APX_Portfolio_Statement> APX_Portfolio_Statement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Benchmark> Portfolio_Benchmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Investment_Objective> Portfolio_Investment_Objective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Performance> Portfolio_Performance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Returns> Portfolio_Returns { get; set; }
    }
}
