//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Account_Attribute = new HashSet<Account_Attribute>();
            this.Account_Benchmark = new HashSet<Account_Benchmark>();
            this.Account_Group_Member = new HashSet<Account_Group_Member>();
            this.Account_Investment_Objective = new HashSet<Account_Investment_Objective>();
            this.Account_Performance = new HashSet<Account_Performance>();
            this.Account_Returns = new HashSet<Account_Returns>();
            this.Account_User_Group = new HashSet<Account_User_Group>();
            this.Account_Strategy_Override = new HashSet<Account_Strategy_Override>();
            this.Current_Positions = new HashSet<Current_Positions>();
            this.Custom_Comment = new HashSet<Custom_Comment>();
            this.Fee_Snapshot = new HashSet<Fee_Snapshot>();
            this.Investment_Action = new HashSet<Investment_Action>();
            this.Investment_Progress = new HashSet<Investment_Progress>();
            this.Investment_Progress_IM = new HashSet<Investment_Progress_IM>();
            this.Investment_Progress_Pre = new HashSet<Investment_Progress_Pre>();
            this.Mapping_Account = new HashSet<Mapping_Account>();
            this.Performance_Alternatives = new HashSet<Performance_Alternatives>();
            this.Realized_GainLoss = new HashSet<Realized_GainLoss>();
            this.Recon_Status = new HashSet<Recon_Status>();
            this.Related_Party = new HashSet<Related_Party>();
            this.SMA_Strategy = new HashSet<SMA_Strategy>();
            this.Tax_Lot_Snapshot = new HashSet<Tax_Lot_Snapshot>();
            this.Tax_Lot = new HashSet<Tax_Lot>();
            this.Account_Transaction = new HashSet<Account_Transaction>();
            this.Transaction_Activity = new HashSet<Transaction_Activity>();
            this.Transaction_Comment = new HashSet<Transaction_Comment>();
            this.Transaction_Snapshot = new HashSet<Transaction_Snapshot>();
            this.Transaction_Snapshot2 = new HashSet<Transaction_Snapshot2>();
            this.Web_Account_Group_Member = new HashSet<Web_Account_Group_Member>();
            this.Web_Supplemental_Access = new HashSet<Web_Supplemental_Access>();
        }
    
        public int id { get; set; }
        public string short_name { get; set; }
        public string long_name { get; set; }
        public string status { get; set; }
        public string tax_status { get; set; }
        public string tax_number { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public int account_class_id { get; set; }
        public Nullable<int> relationship_id { get; set; }
        public int custodian_id { get; set; }
        public string custodian_account_code { get; set; }
        public int asset_manager_id { get; set; }
        public Nullable<double> initial_value { get; set; }
        public Nullable<System.DateTime> recon_close_date { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> perf_start_date { get; set; }
        public Nullable<int> family_group_id { get; set; }
        public string long_name_2 { get; set; }
        public string long_name_3 { get; set; }
        public Nullable<System.DateTime> progress_start_date { get; set; }
        public int account_type_id { get; set; }
        public bool is_institution { get; set; }
        public bool is_new_client { get; set; }
        public bool is_existing_funds { get; set; }
        public int close_reason_id { get; set; }
        public bool is_erisa { get; set; }
        public bool active { get; set; }
    
        public virtual Account_Class Account_Class { get; set; }
        public virtual Account_Type Account_Type { get; set; }
        public virtual Asset_Manager Asset_Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Attribute> Account_Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Benchmark> Account_Benchmark { get; set; }
        public virtual Account_Close_Reason Account_Close_Reason { get; set; }
        public virtual Source Source { get; set; }
        public virtual Family_Group Family_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Group_Member> Account_Group_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Investment_Objective> Account_Investment_Objective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Performance> Account_Performance { get; set; }
        public virtual Relationship Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Returns> Account_Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_User_Group> Account_User_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Strategy_Override> Account_Strategy_Override { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_Positions> Current_Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custom_Comment> Custom_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee_Snapshot> Fee_Snapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Action> Investment_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Progress> Investment_Progress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Progress_IM> Investment_Progress_IM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Progress_Pre> Investment_Progress_Pre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping_Account> Mapping_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance_Alternatives> Performance_Alternatives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realized_GainLoss> Realized_GainLoss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recon_Status> Recon_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Related_Party> Related_Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMA_Strategy> SMA_Strategy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Lot_Snapshot> Tax_Lot_Snapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Lot> Tax_Lot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Transaction> Account_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Activity> Transaction_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Comment> Transaction_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Snapshot> Transaction_Snapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Snapshot2> Transaction_Snapshot2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Account_Group_Member> Web_Account_Group_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Supplemental_Access> Web_Supplemental_Access { get; set; }
    }
}
