//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Allocation_Target
    {
        public int investment_goal_id { get; set; }
        public int classification_id { get; set; }
        public double lower_bound { get; set; }
        public double upper_bound { get; set; }
        public double suggested_value { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual Investment_Goal Investment_Goal { get; set; }
    }
}
