//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUM_Fund_Mapping
    {
        public string fund_prefix { get; set; }
        public string fund_name { get; set; }
        public string fund_company { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    }
}
