//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUM_Revenue_Source
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUM_Revenue_Source()
        {
            this.Revenue_Snapshot = new HashSet<Revenue_Snapshot>();
        }
    
        public int id { get; set; }
        public string short_name { get; set; }
        public string long_name { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenue_Snapshot> Revenue_Snapshot { get; set; }
    }
}
