//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Request()
        {
            this.Book_Request_Detail = new HashSet<Book_Request_Detail>();
        }
    
        public int id { get; set; }
        public int template_id { get; set; }
        public string destination { get; set; }
        public string request_status { get; set; }
        public int priority { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int document_type_id { get; set; }
        public string err_message { get; set; }
        public Nullable<int> firm_user_group_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Request_Detail> Book_Request_Detail { get; set; }
        public virtual Web_Document_Type Web_Document_Type { get; set; }
        public virtual Template Template { get; set; }
    }
}
