//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classification()
        {
            this.Account_Benchmark = new HashSet<Account_Benchmark>();
            this.Account_Performance = new HashSet<Account_Performance>();
            this.Asset_Allocation_Target = new HashSet<Asset_Allocation_Target>();
            this.Asset_Class_Equivalent = new HashSet<Asset_Class_Equivalent>();
            this.Asset_Class_Equivalent1 = new HashSet<Asset_Class_Equivalent>();
            this.Account_Returns = new HashSet<Account_Returns>();
            this.Classification_Sort = new HashSet<Classification_Sort>();
            this.Investment_Progress = new HashSet<Investment_Progress>();
            this.Investment_Progress_IM = new HashSet<Investment_Progress_IM>();
            this.Investment_Progress_Pre = new HashSet<Investment_Progress_Pre>();
            this.Portfolio_Benchmark = new HashSet<Portfolio_Benchmark>();
            this.Portfolio_Performance = new HashSet<Portfolio_Performance>();
            this.Portfolio_Returns = new HashSet<Portfolio_Returns>();
            this.SAMG_Strategy = new HashSet<SAMG_Strategy>();
            this.Security_Classification = new HashSet<Security_Classification>();
            this.Strategies = new HashSet<Strategy>();
            this.Tax_Lot_Snapshot = new HashSet<Tax_Lot_Snapshot>();
        }
    
        public int id { get; set; }
        public int scheme_id { get; set; }
        public int grouping_id_1 { get; set; }
        public int grouping_id_2 { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Benchmark> Account_Benchmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Performance> Account_Performance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Allocation_Target> Asset_Allocation_Target { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Class_Equivalent> Asset_Class_Equivalent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Class_Equivalent> Asset_Class_Equivalent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Returns> Account_Returns { get; set; }
        public virtual Entity_Grouping Entity_Grouping { get; set; }
        public virtual Entity_Grouping Entity_Grouping1 { get; set; }
        public virtual Scheme Scheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classification_Sort> Classification_Sort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Progress> Investment_Progress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Progress_IM> Investment_Progress_IM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Progress_Pre> Investment_Progress_Pre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Benchmark> Portfolio_Benchmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Performance> Portfolio_Performance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio_Returns> Portfolio_Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAMG_Strategy> SAMG_Strategy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_Classification> Security_Classification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strategy> Strategies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Lot_Snapshot> Tax_Lot_Snapshot { get; set; }
    }
}
