//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entity_Document()
        {
            this.Entity_Document_Delivery = new HashSet<Entity_Document_Delivery>();
        }
    
        public System.DateTime from_date { get; set; }
        public System.DateTime thru_date { get; set; }
        public int contact_id { get; set; }
        public int entity_id { get; set; }
        public bool is_group { get; set; }
        public bool is_dw_group { get; set; }
        public int template_id { get; set; }
        public int document_type_id { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_Document_Delivery> Entity_Document_Delivery { get; set; }
        public virtual Template Template { get; set; }
    }
}
