//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intra_Month_Data_Tracker
    {
        public System.DateTime as_of_date { get; set; }
        public string data_type { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    }
}
