//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestCloud_Contact
    {
        public string username { get; set; }
        public string email_address { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string entity_code { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
