//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Investment_Objective
    {
        public int account_group_id { get; set; }
        public int investment_goal_id { get; set; }
        public System.DateTime objective_date { get; set; }
        public int item_id { get; set; }
        public string item_value { get; set; }
        public int display_order { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Account_Group Account_Group { get; set; }
        public virtual Investment_Goal Investment_Goal { get; set; }
        public virtual Investment_Objective_Item Investment_Objective_Item { get; set; }
    }
}
