//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realized_GainLoss
    {
        public int source_id { get; set; }
        public int currency_id { get; set; }
        public int account_id { get; set; }
        public int transaction_id { get; set; }
        public int security_id { get; set; }
        public string bond_description { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public System.DateTime close_date { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> proceeds { get; set; }
        public Nullable<double> cost_basis { get; set; }
        public Nullable<double> amortization { get; set; }
        public int holding_duration_id { get; set; }
        public int lot_number { get; set; }
        public double realized_gl { get; set; }
        public double realized_gl_fx { get; set; }
        public double realized_gl_st { get; set; }
        public double realized_gl_lt { get; set; }
        public double realized_gl_5y { get; set; }
        public double realized_gl_price { get; set; }
        public bool is_capital_gain { get; set; }
        public string mutual_fund_account { get; set; }
        public bool is_unsupervised { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Security Security { get; set; }
        public virtual Source Source { get; set; }
    }
}
