//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Formula
    {
        public int id { get; set; }
        public string code { get; set; }
        public string param_type { get; set; }
        public string description { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public int sort_order { get; set; }
    }
}
