//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Param
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report_Param()
        {
            this.Book_Request_Detail = new HashSet<Book_Request_Detail>();
            this.Report_Param_Access = new HashSet<Report_Param_Access>();
            this.Report_Param_Mapping = new HashSet<Report_Param_Mapping>();
            this.Template_Report_Detail = new HashSet<Template_Report_Detail>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string param_type { get; set; }
        public string param_dataset_function { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Request_Detail> Book_Request_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_Param_Access> Report_Param_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report_Param_Mapping> Report_Param_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template_Report_Detail> Template_Report_Detail { get; set; }
    }
}
