//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue_Snapshot
    {
        public System.DateTime from_date { get; set; }
        public System.DateTime thru_date { get; set; }
        public int revenue_source_id { get; set; }
        public int firm_user_group_id { get; set; }
        public int family_group_id { get; set; }
        public double amount { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    
        public virtual AUM_Revenue_Source AUM_Revenue_Source { get; set; }
        public virtual Family_Group Family_Group { get; set; }
        public virtual Firm_User_Group Firm_User_Group { get; set; }
    }
}
