//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAMG_Strategy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAMG_Strategy()
        {
            this.Web_Strategy_Document = new HashSet<Web_Strategy_Document>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string display_name { get; set; }
        public int classification_id { get; set; }
        public int sort_order { get; set; }
    
        public virtual Classification Classification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Strategy_Document> Web_Strategy_Document { get; set; }
    }
}
