//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Snapshot
    {
        public System.DateTime as_of_date { get; set; }
        public int security_id { get; set; }
        public int security_type_id { get; set; }
        public string symbol { get; set; }
        public int country_id_dom { get; set; }
        public int currency_id_dom { get; set; }
        public int state_id { get; set; }
        public int currency_id_exch { get; set; }
        public int exchange_id { get; set; }
        public Nullable<int> underlying_security_id { get; set; }
        public Nullable<double> valuation_factor { get; set; }
        public string sector { get; set; }
        public string industry { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Exchange Exchange { get; set; }
        public virtual Security_Type Security_Type { get; set; }
        public virtual State1 State1 { get; set; }
    }
}
