//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Security()
        {
            this.Account_Transaction = new HashSet<Account_Transaction>();
            this.Asset_Class_Equivalent = new HashSet<Asset_Class_Equivalent>();
            this.Current_Positions = new HashSet<Current_Positions>();
            this.Investment_Action = new HashSet<Investment_Action>();
            this.Performance_Alternatives = new HashSet<Performance_Alternatives>();
            this.Prices = new HashSet<Price>();
            this.Realized_GainLoss = new HashSet<Realized_GainLoss>();
            this.Security_Attribute = new HashSet<Security_Attribute>();
            this.Security_Classification = new HashSet<Security_Classification>();
            this.Small_Cap_Trade = new HashSet<Small_Cap_Trade>();
            this.Tax_Lot = new HashSet<Tax_Lot>();
            this.Tax_Lot_Snapshot = new HashSet<Tax_Lot_Snapshot>();
            this.Transaction_Activity = new HashSet<Transaction_Activity>();
            this.Transaction_Snapshot = new HashSet<Transaction_Snapshot>();
            this.Transaction_Snapshot2 = new HashSet<Transaction_Snapshot2>();
        }
    
        public int id { get; set; }
        public string symbol_type_code { get; set; }
        public int security_type_id { get; set; }
        public string symbol { get; set; }
        public string cusip { get; set; }
        public string ticker { get; set; }
        public string isin { get; set; }
        public string sedol { get; set; }
        public string proprietary { get; set; }
        public string name { get; set; }
        public int country_id_dom { get; set; }
        public int currency_id_dom { get; set; }
        public int currency_id_exch { get; set; }
        public int exchange_id { get; set; }
        public Nullable<double> coupon_rate { get; set; }
        public Nullable<System.DateTime> maturity_date { get; set; }
        public Nullable<int> payment_frequency { get; set; }
        public Nullable<int> underlying_security_id { get; set; }
        public Nullable<double> valuation_factor { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int state_id { get; set; }
        public int source_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Transaction> Account_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Class_Equivalent> Asset_Class_Equivalent { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_Positions> Current_Positions { get; set; }
        public virtual Exchange Exchange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment_Action> Investment_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance_Alternatives> Performance_Alternatives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Prices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realized_GainLoss> Realized_GainLoss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_Attribute> Security_Attribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_Classification> Security_Classification { get; set; }
        public virtual Security_Type Security_Type { get; set; }
        public virtual Source Source { get; set; }
        public virtual State1 State1 { get; set; }
        public virtual Security_Strategy Security_Strategy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Small_Cap_Trade> Small_Cap_Trade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Lot> Tax_Lot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Lot_Snapshot> Tax_Lot_Snapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Activity> Transaction_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Snapshot> Transaction_Snapshot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Snapshot2> Transaction_Snapshot2 { get; set; }
    }
}
