//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Fee_Snapshot
    {
        public bool is_active { get; set; }
        public System.DateTime as_of_date { get; set; }
        public string account_code { get; set; }
        public string symbol { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> security_id { get; set; }
        public Nullable<double> gross_fee { get; set; }
    }
}
