//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Account
    {
        public bool is_active { get; set; }
        public int source_id { get; set; }
        public int account_id { get; set; }
        public string account_code { get; set; }
        public string short_name { get; set; }
        public string long_name { get; set; }
        public int account_type_id { get; set; }
        public string status { get; set; }
        public string tax_status { get; set; }
        public string tax_number { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public int close_reason_id { get; set; }
        public int account_class_id { get; set; }
        public Nullable<int> relationship_id { get; set; }
        public Nullable<int> family_group_id { get; set; }
        public int custodian_id { get; set; }
        public string custodian_account_code { get; set; }
        public int asset_manager_id { get; set; }
        public bool is_institution { get; set; }
        public bool is_erisa { get; set; }
        public bool is_new_client { get; set; }
        public bool is_existing_funds { get; set; }
        public Nullable<double> initial_value { get; set; }
        public Nullable<System.DateTime> recon_close_date { get; set; }
        public Nullable<System.DateTime> perf_start_date { get; set; }
        public string long_name_2 { get; set; }
        public string long_name_3 { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string delete_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
    }
}
