//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Tax_Lot_Pre
    {
        public string SourceName { get; set; }
        public System.DateTime AsOfDate { get; set; }
        public string PortfolioCode { get; set; }
        public string Symbol { get; set; }
        public string PrincipalCurrencyCode { get; set; }
        public string SecTypeCode { get; set; }
        public int LotNumber { get; set; }
        public bool IsShort { get; set; }
        public bool IsUnsupervised { get; set; }
        public double APXQuantity { get; set; }
        public double APXUnadjustedQuantity { get; set; }
        public string HoldCode { get; set; }
        public double LocalMarketValue { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<double> LocalAccruedInterest { get; set; }
        public Nullable<double> LocalAnnualIncome { get; set; }
        public Nullable<double> LocalCostBasis { get; set; }
        public double LocalUnadjustedCostBasis { get; set; }
        public double APXLocalPrice { get; set; }
        public Nullable<double> LocalUnitCost { get; set; }
        public double LocalUnadjustedUnitCost { get; set; }
        public Nullable<double> LocalUnrealizedGainLoss { get; set; }
        public Nullable<double> UnrealizedGainLossFX { get; set; }
        public Nullable<double> YTMOnCost { get; set; }
        public Nullable<double> DurationOnCost { get; set; }
        public Nullable<double> Yield { get; set; }
    }
}
