//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Classification_Sort
    {
        public bool is_active { get; set; }
        public int scheme_id { get; set; }
        public int classification_id { get; set; }
        public int sort_order { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    }
}
