//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_IShares
    {
        public bool is_active { get; set; }
        public System.DateTime as_of_date { get; set; }
        public string etf_ticker { get; set; }
        public double etf_assets { get; set; }
        public string sedol { get; set; }
        public string isin { get; set; }
        public string ticker { get; set; }
        public string security_name { get; set; }
        public string asset_class { get; set; }
        public double shares { get; set; }
        public double price { get; set; }
        public double market_value { get; set; }
        public double etf_weight { get; set; }
        public string gics_sector { get; set; }
        public string exchange { get; set; }
        public string country { get; set; }
        public string currency { get; set; }
        public string currency_exch { get; set; }
        public Nullable<double> fx_rate { get; set; }
        public Nullable<int> security_id { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> classification_id { get; set; }
        public Nullable<int> country_id { get; set; }
    }
}
