//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Revenue_Snapshot
    {
        public bool is_active { get; set; }
        public System.DateTime as_of_date { get; set; }
        public string revenue_source { get; set; }
        public Nullable<int> revenue_source_id { get; set; }
        public string mgr_code { get; set; }
        public Nullable<int> mgr_id { get; set; }
        public string fg_or_fd_name { get; set; }
        public string fg_or_fd { get; set; }
        public Nullable<int> family_group_id { get; set; }
        public string reclassify_from_advisory { get; set; }
        public string only_rep_accounts { get; set; }
        public double fee_amount { get; set; }
    }
}
