//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Performance_Alternatives
    {
        public bool is_active { get; set; }
        public string period_to_date { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime thru_date { get; set; }
        public int account_id { get; set; }
        public int security_id { get; set; }
        public bool is_short { get; set; }
        public bool is_unsupervised { get; set; }
        public System.DateTime commitment_date { get; set; }
        public double committed_capital_1 { get; set; }
        public double committed_capital_2 { get; set; }
        public double final_commitment { get; set; }
        public double contributed_capital_1 { get; set; }
        public double contributed_capital_2 { get; set; }
        public double unfunded_commitment_1 { get; set; }
        public double unfunded_commitment_2 { get; set; }
        public double distributed_cost_nr_1 { get; set; }
        public double distributed_cost_nr_2 { get; set; }
        public double distributed_cost_r_1 { get; set; }
        public double distributed_cost_r_2 { get; set; }
        public double distributed_gains_nr_1 { get; set; }
        public double distributed_gains_nr_2 { get; set; }
        public double distributed_gains_r_1 { get; set; }
        public double distributed_gains_r_2 { get; set; }
        public double market_value_1 { get; set; }
        public double market_value_2 { get; set; }
        public double cost_basis { get; set; }
        public double realized_gl_cost { get; set; }
        public double realized_gl_mv { get; set; }
        public double unrealized_gl_cost { get; set; }
        public double unrealized_gl_mv { get; set; }
        public double realized_gl_fx { get; set; }
        public double unrealized_gl_fx { get; set; }
        public double dividends { get; set; }
        public double interest { get; set; }
        public double contributions { get; set; }
        public double withdrawals { get; set; }
        public double transfers_in { get; set; }
        public double transfers_out { get; set; }
        public double fees { get; set; }
        public double port_fees { get; set; }
        public double management_fees { get; set; }
        public double port_fees_paid_by_client { get; set; }
        public double mgmt_fees_paid_by_client { get; set; }
        public double IRR { get; set; }
        public double annualized_IRR { get; set; }
        public System.DateTime annualization_from_date { get; set; }
        public System.DateTime annualization_thru_date { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
