//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Statement_Delivery_Queue
    {
        public int sequence_num { get; set; }
        public System.DateTime as_of_date { get; set; }
        public int contact_id { get; set; }
        public int delivery_type_id { get; set; }
        public string manager_code { get; set; }
        public string request_by { get; set; }
        public System.DateTime request_date_UTC { get; set; }
    }
}
