//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement_Queue
    {
        public System.DateTime as_of_date { get; set; }
        public int entity_id { get; set; }
        public int is_group { get; set; }
        public int template_id { get; set; }
        public int document_type_id { get; set; }
        public Nullable<System.DateTime> dw_refreshed_UTC { get; set; }
        public bool is_reconciled { get; set; }
        public Nullable<System.DateTime> perf_calc_date_UTC { get; set; }
        public int is_gross { get; set; }
        public int book_request_id { get; set; }
        public string comments { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public bool is_derived_from_combined { get; set; }
        public Nullable<System.DateTime> reconciled_date_UTC { get; set; }
    }
}
