//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement_Upload_Queue
    {
        public System.DateTime as_of_date { get; set; }
        public int entity_id { get; set; }
        public bool is_group { get; set; }
        public int template_id { get; set; }
        public int delivery_type_id { get; set; }
        public Nullable<System.DateTime> request_date_UTC { get; set; }
        public Nullable<System.DateTime> completion_date_UTC { get; set; }
        public string destination { get; set; }
    
        public virtual Document_Delivery_Type Document_Delivery_Type { get; set; }
    }
}
