//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strategy_Allocation_Target
    {
        public int allocation_risk_profile_id { get; set; }
        public bool includes_alternatives { get; set; }
        public int strategy_id { get; set; }
        public double suggested_value { get; set; }
    
        public virtual Allocation_Risk_Profile Allocation_Risk_Profile { get; set; }
        public virtual Strategy Strategy { get; set; }
    }
}
