//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Lot_Snapshot
    {
        public System.DateTime as_of_date { get; set; }
        public int classification_id { get; set; }
        public int account_id { get; set; }
        public int security_id { get; set; }
        public int security_type_id { get; set; }
        public string symbol { get; set; }
        public int currency_id_exch { get; set; }
        public int lot_number { get; set; }
        public bool is_short { get; set; }
        public bool is_unsupervised { get; set; }
        public double quantity { get; set; }
        public Nullable<double> price { get; set; }
        public double market_value { get; set; }
        public Nullable<System.DateTime> original_cost_date { get; set; }
        public Nullable<double> accrued_interest { get; set; }
        public Nullable<double> annual_income { get; set; }
        public Nullable<double> cost_basis { get; set; }
        public Nullable<double> unit_cost { get; set; }
        public Nullable<double> fx_rate_usd { get; set; }
        public string security_name { get; set; }
        public string bond_description { get; set; }
        public string fund_name { get; set; }
        public Nullable<double> yield { get; set; }
        public double valuation_factor { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Classification Classification { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Security Security { get; set; }
        public virtual Security_Type Security_Type { get; set; }
    }
}
