//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Activity
    {
        public int source_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime trade_date { get; set; }
        public Nullable<System.DateTime> settle_date { get; set; }
        public int tran_type_id { get; set; }
        public int security_id_1 { get; set; }
        public Nullable<int> security_id_2 { get; set; }
        public Nullable<double> quantity { get; set; }
        public double trade_amount { get; set; }
        public Nullable<double> original_cost { get; set; }
        public int lot_number { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Security Security { get; set; }
        public virtual Transaction_Type Transaction_Type { get; set; }
    }
}
