//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Exited_Assets
    {
        public int source_id { get; set; }
        public int transaction_id { get; set; }
        public int account_id { get; set; }
        public Nullable<System.DateTime> original_cost_date { get; set; }
        public double cost_basis { get; set; }
        public double unadjusted_cost_basis { get; set; }
        public double amortization_mtd { get; set; }
        public double amortization_ytd { get; set; }
        public double amortization_ttd { get; set; }
        public string bond_status_code { get; set; }
        public Nullable<System.DateTime> bond_status_date { get; set; }
        public string bond_description { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
