//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Comment_Aligned
    {
        public int source_id { get; set; }
        public int transaction_id { get; set; }
        public int account_id { get; set; }
        public int transaction_comment_id_start { get; set; }
        public int transaction_comment_id_end { get; set; }
        public System.DateTime trade_date { get; set; }
        public string comment { get; set; }
    }
}
