//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Strategy_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Web_Strategy_Document()
        {
            this.Web_Strategy_Document_Favorite = new HashSet<Web_Strategy_Document_Favorite>();
        }
    
        public int id { get; set; }
        public string file_id { get; set; }
        public int samg_strategy_id { get; set; }
        public bool is_institutional { get; set; }
        public System.DateTime document_date { get; set; }
        public System.DateTime upload_date { get; set; }
    
        public virtual SAMG_Strategy SAMG_Strategy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Strategy_Document_Favorite> Web_Strategy_Document_Favorite { get; set; }
    }
}
