//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Login_Session_Record
    {
        public int id { get; set; }
        public string web_user_id { get; set; }
        public Nullable<int> minutes_online { get; set; }
        public System.DateTime login_date { get; set; }
        public Nullable<System.DateTime> logout_date { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public System.DateTime update_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
