//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Security_Answer
    {
        public int id { get; set; }
        public string web_user_id { get; set; }
        public int question_id { get; set; }
        public string answer_hash { get; set; }
        public string insert_by { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Web_Security_Question Web_Security_Question { get; set; }
    }
}
