//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvercrest.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Email_Alerts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Web_Email_Alerts()
        {
            this.Web_Email_Alert_Documents = new HashSet<Web_Email_Alert_Documents>();
        }
    
        public int id { get; set; }
        public bool is_active { get; set; }
        public string recipient { get; set; }
        public Nullable<int> from_contact_id { get; set; }
        public System.DateTime delivery_date { get; set; }
        public System.DateTime insert_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Email_Alert_Documents> Web_Email_Alert_Documents { get; set; }
    }
}
